let
 // =====================================================
 // CAMINHO DA PASTA
 // =====================================================
 CaminhoPastaPDFs =
 "C:\Users\lucas.nathan\OneDrive - ALLOS\Área de Trabalho\AnexosPO",

 // =====================================================
 // HELPERS
 // =====================================================
 nzText = (t as nullable text) as text =>
 if t = null then "" else Text.From(t),

 fnNormalizeSoft = (t as nullable text) as text =>
 if t = null then ""
 else
 let
 s0 = Text.Clean(t),
 s1 = Text.Replace(Text.Replace(Text.Replace(s0, "#(lf)", " "), "#(cr)", " "), "#(tab)", " "),
 s2 = Text.Replace(s1, Character.FromNumber(160), " "),
 tokens = List.Select(Text.Split(s2, " "), each _ <> ""),
 out = Text.Combine(tokens, " ")
 in
 out,

 fnDataBlockToTextRaw = (dataBlock as any) as text =>
 if (dataBlock = null) or (not (dataBlock is table)) then nzText(dataBlock)
 else
 let
 rows = Table.ToRows(dataBlock),
 rowTexts = List.Transform(rows, each Text.Combine(List.Transform(_, nzText), " ")),
 out = Text.Combine(rowTexts, "#(lf)")
 in
 out,

 fnGetTextoPagina1Raw = (pdfTables as nullable table) as text =>
 if pdfTables = null then ""
 else
 let
 pag1 =
 if Table.HasColumns(pdfTables, "Page")
 then Table.SelectRows(pdfTables, each [Page] = 1)
 else Table.FirstN(pdfTables, 1),
 blocos = try Table.Column(pag1, "Data") otherwise {},
 out = Text.Combine(List.Transform(blocos, fnDataBlockToTextRaw), "#(lf)")
 in
 out,

 fnTextNoSpacesKeepDigits = (t as nullable text) as text =>
 if t = null then ""
 else
 let
 s0 = Text.Remove(t, {" ", "#(lf)", "#(cr)", "#(tab)", "|", "¦", "｜", Character.FromNumber(160)})
 in
 s0,

 fnOnlyLettersAndPunct = (t as nullable text) as text =>
 if t = null then ""
 else
 let
 s0 = Text.Remove(t, {"|", "¦", "｜", "#(lf)", "#(cr)", "#(tab)", " ", Character.FromNumber(160)}),
 chars = Text.ToList(s0),
 out = Text.Combine(List.Select(chars, each not List.Contains({"0".."9"}, _)), "")
 in
 out,

 fnIsPO = (t as nullable text) as logical =>
 if t = null then false
 else
 let x = Text.Lower(fnNormalizeSoft(t))
 in Text.Contains(x, "ordem de compra") or Text.Contains(x, "ordemdecompra"),

 // =====================================================
 // PEDIDO
 // =====================================================
 fnExtractPedidoFromPag1 = (t as nullable text) as nullable text =>
 if t = null then null
 else
 let
 texto = fnNormalizeSoft(t),
 dig = Text.Combine(List.Transform(Text.ToList(texto), each if List.Contains({"0".."9"}, _) then _ else " "), ""),
 tokens = List.Select(Text.Split(dig, " "), each Text.StartsWith(_, "45")),
 out = if List.Count(tokens) > 0 then Text.Start(tokens{0}, 10) else null
 in
 out,

 // =====================================================
 // SAP – EXATAMENTE 8 DÍGITOS (OBRIGATÓRIO)
 // =====================================================
 fnExtractSAPFromPag1 = (t as nullable text) as nullable text =>
 if t = null then null
 else
 let
 texto = fnNormalizeSoft(t),
 low = Text.Lower(texto),

 pos =
 if Text.PositionOf(low, "código:") >= 0 then Text.PositionOf(low, "código:")
 else if Text.PositionOf(low, "codigo:") >= 0 then Text.PositionOf(low, "codigo:")
 else -1,

 trecho = if pos < 0 then null else Text.Middle(texto, pos, 50),

 digEsp =
 if trecho = null then null
 else
 Text.Combine(
 List.Transform(Text.ToList(trecho), each if List.Contains({"0".."9"}, _) then _ else " "),
 ""
 ),

 tokens = if digEsp = null then {} else List.Select(Text.Split(digEsp, " "), each _ <> ""),
 num = if List.Count(tokens) > 0 then tokens{0} else null,

 sap =
 if num = null then null
 else
 let
 base =
 if Text.StartsWith(num, "0010") then "10" & Text.Range(num, 4)
 else Text.TrimStart(num, {"0"}),

 out = if Text.Length(base) = 8 then base else null
 in
 out
 in
 sap,

 // =====================================================
 // CNPJ
 // =====================================================
 fnExtractCNPJComMascara = (t as nullable text) as nullable text =>
 if t = null then null
 else
 let
 txt = Text.Upper(fnNormalizeSoft(t)),
 cand =
 List.RemoveNulls(
 List.Transform(
 List.Generate(() => 0, each _ <= Text.Length(txt) - 18, each _ + 1, each Text.Middle(txt, _, 18)),
 each
 if Text.Length(_) = 18
 and Text.Middle(_,2,1)="."
 and Text.Middle(_,6,1)="."
 and Text.Middle(_,10,1)="/"
 and Text.Middle(_,15,1)="-"
 then _ else null
 )
 )
 in
 if List.Count(cand) > 0 then cand{0} else null,

 // =====================================================
 // VALOR
 // =====================================================
 fnExtractValorFromPag1 = (t as nullable text) as nullable number =>
 if t = null then null
 else
 let
 txt = fnNormalizeSoft(t),
 chars = Text.ToList(txt),
 limpo = Text.Combine(List.Transform(chars, each if List.Contains({"0".."9",".",","," "}, _) then _ else " "), ""),
 tokens = List.Select(Text.Split(limpo, " "), each Text.Contains(_, ",")),
 vals = List.RemoveNulls(List.Transform(tokens, each try Number.FromText(_, "pt-BR") otherwise null))
 in
 if List.Count(vals) > 0 then List.Max(vals) else null,

 // =====================================================
 // PIPELINE
 // =====================================================
 Fonte = Folder.Files(CaminhoPastaPDFs),
 ApenasPDF = Table.SelectRows(Fonte, each Text.Lower([Extension]) = ".pdf"),
 PdfLido = Table.AddColumn(ApenasPDF, "Pdf", each try Pdf.Tables([Content]) otherwise null),
 TextoRaw = Table.AddColumn(PdfLido, "TEXTO_PAG1_RAW", each fnGetTextoPagina1Raw([Pdf])),
 SomentePO = Table.SelectRows(TextoRaw, each fnIsPO([TEXTO_PAG1_RAW])),

 AddPedido = Table.AddColumn(SomentePO, "PEDIDO", each fnExtractPedidoFromPag1([TEXTO_PAG1_RAW])),
 AddSAP = Table.AddColumn(AddPedido, "COD SAP", each fnExtractSAPFromPag1([TEXTO_PAG1_RAW])),
 AddCNPJ = Table.AddColumn(AddSAP, "CNPJ", each fnExtractCNPJComMascara([TEXTO_PAG1_RAW])),
 AddValor = Table.AddColumn(AddCNPJ, "VALOR", each fnExtractValorFromPag1([TEXTO_PAG1_RAW])),
 AddTexto = Table.AddColumn(AddValor, "TEXTO_PAG1", each fnTextNoSpacesKeepDigits([TEXTO_PAG1_RAW])),

 // ✅ FILTRA SOMENTE SAP VÁLIDO (8 DÍGITOS)
 FiltraSAP8 =
 Table.SelectRows(
 AddTexto,
 each [COD SAP] <> null and Text.Length([COD SAP]) = 8
 ),

 ResultadoFinal =
 Table.SelectColumns(
 FiltraSAP8,
 {"PEDIDO", "TEXTO_PAG1", "COD SAP", "CNPJ", "VALOR"}
 ),

 #"Tipo Alterado" = Table.TransformColumnTypes(ResultadoFinal,{{"PEDIDO", Int64.Type}})
 in
 #"Tipo Alterado"